name: Deploy React App to GitHub Pages

# This workflow deploys a React app to GitHub Pages whenever there is a push to the main branch or when manually triggered.
on: [workflow_dispatch]


jobs:
  #run the tests before deploying
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: print node version
        run: node -v
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build React app
        run: npm run build
      - name: upload dist artifact
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          name: github-pages
          path: dist
  deploy:
     needs: build
     permissions:
        pages: write      # to deploy to Pages
        id-token: write   # to verify the deployment originates from an appropriate source
     environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
       with:
          token: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN secret is automatically created by GitHub and is used to authenticate the workflow with the repository.
    

